### ISSUE TITLE
Unable to open in fullscreen

### ISSUE THREAD

**Issue by robbforce** [MartyShepard/Dosbox--Optionals-#2]
I've been using the daum build to open fullscreen and apply a CRT shader, but I haven't been able to do the same with this build so far. Certainly user error. I'm attaching my conf files as txt. Maybe you have ideas?
[dosbox.txt](https://github.com/MartyShepard/Dosbox--Optionals-/files/1997970/dosbox.txt)
[dosbox-opt.txt](https://github.com/MartyShepard/Dosbox--Optionals-/files/1997971/dosbox-opt.txt)

I run dosbox by specifying this conf file and append another that has custom settings per game, as well as the autoexec commands.

**Comment by robbforce** [comment]
I messed around with the settings some more. It seems like fullscreen is not a true full screen, but a borderless window. Using fullscreen=true, fullresolution=desktop, and windowresolution=original, I get a 320x200 screen in the upper left corner, with my desktop displayed behind it. If I change windowresolution to 1920x1080, I get a window with the correct aspect height (1080), but still on the left edge with my desktop displayed on the right. If I set fullscreen=false, the window is now displayed in the center. Not sure why window settings would be doing anything in fullscreen mode, ultimately.

Also, I had to set output=openglnb to get any screen size changes with fullscreen=true, otherwise with texturenb I only get a small 320x200 window, no matter what I change, and no shader is applied.

**Comment by MartyShepard** [comment]
Hello,
I had this noted in the optionals.txt

NOTE: Fullscreen issues and todos.   
I think you have already noticed. The whole thing with the fullscreen somehow not working properly.
I therefore advise you to avoid the fullscreen. Why?
- With the method Output = Surface, image remains black.
- With the method Output = Texture (nb), Fullscreen does not work in combination with a specified fullscreen resolution. Result: graphic error
- With the method Output = OpenGL (nb), see above.
- 3DFX. It may happen that crashes with the method OpenGL (nb) and Native Fullscreen Dosbox.
- When you quit Dosbox in fullscreen mode. Keys entered or in the DosShell "exit". Dosbox crashes.

I know. These are important things that need to be done.

I had not really time to repair the Fullscreen. I'm really happy for any help.

**Comment by robbforce** [comment]
I've got dosbox svn compiling in visual studio 2017 now and I like the way you organized the project, so I'm going to commit the current svn project, then start re-organizing the svn project to match yours, make sure it still compiles, commit those changes, then introduce your fixes, one at a time, test, commit, etc. It's going to be tedious, but it's probably the only way to find out what is causing the fullscreen issues, since your commit history seems to begin after you applied all the patches.

If you remember the changes you made to SVN to re-organize it, that would be a great start for your repo. Then if you still have the individual patches, they could be applied one by one with commits in-between and you can rollback to find the offending code that's causing the issues you listed.

**Comment by MartyShepard** [comment]
Hello,
The Fullscreen Error goes back with the Release from dugan. Look at https://github.com/duganchen/dosbox . This was the Main base i used this. https://www.vogons.org/viewtopic.php?f=41&t=43068

I have the Patches and i can Roll back my Source and save the changes as diff.

greetings

**Comment by robbforce** [comment]
If the error originates with dugan’s fork, what do you think about starting with another base? Yesterplay80’s fork (Dosbox ECE, https://blog.yesterplay80.net/dosbox-ece-en/) seems concise. I’ve got his compiling now in visual studio as well and things appear to be in order. I’ve been building dosbox in visual studio and vcpkg, since the IDE provides decent intellisense and debugging tools. I’ve created a repo with svn and ece branches that compile, if you’re interested in creating a new fork and starting from there. https://github.com/robbforce/dosbox

I’m thinking I’ll merge the ece branch into master, then see if I can pull in some of your changes.

________________________________

**Comment by robbforce** [comment]
I managed to update dosbox-ece to SDL2 and get it to build, but it also has the same problem with fullscreen. Ultimately a waste of effort, but I learned a lot about C++, building C++ projects in Visual Studio 2017, and some upconversions to SDL2! What I think I'll do now is try to apply what I learned to your project to get it building in VS2017 first, which will give access to debugging and step through code, then start researching about SDL2 full screen.

**Comment by MartyShepard** [comment]
Hello, Yes it need a litte bit more to work because the Fullscreen. SDL2 has Fullscreen-Window as Fullscreen Default. I begin and changed this in the Voodoo Sources (Real Fullscreen). It need to add as Possible third value. 1 Window/ 2 Fullscreen/ 3. Fullscreen-Window.

**Comment by robbforce** [comment]
I tried and tried to get this all built in windows with visual studio and mostly succeeded, except getting munt to load correctly. It appears to compile and build, but no matter what, my mt-32 lib will not produce sound. It doesn't even have an error in dosbox and comes up in the /listmidi command. Fluidsynth worked just fine. I even got the mt-32 lib to work with the standalone midi player, but it just won't work in dosbox for me. I've run out of ideas.
